export const s = {
  root: {
    minHeight: "100vh",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    background: "#0D0D0D",
    fontFamily: "'DM Sans', sans-serif",
    padding: "2rem",
  },
  card: {
    width: "100%",
    maxWidth: 420,
    background: "#161616",
    border: "1px solid #2E2E2E",
    borderRadius: 20,
    padding: "2rem",
  },
  logo:     { display: "flex", alignItems: "center", gap: 10, marginBottom: "2rem" },
  logoIcon: {
    width: 36, height: 36, background: "#E8500A",
    borderRadius: 10, display: "flex", alignItems: "center",
    justifyContent: "center", fontSize: 18,
  },
  logoText: { fontFamily: "serif", fontSize: 20, color: "#F5F5F5" },
  h1:       { fontSize: 22, fontWeight: 500, color: "#F5F5F5", marginBottom: 6 },
  subtitle: { color: "#888", fontSize: 14, marginBottom: "1.5rem" },
  label: {
    fontSize: 12, color: "#888", display: "block",
    marginBottom: 6, letterSpacing: "0.04em", textTransform: "uppercase",
  },
  input: (err) => ({
    width: "100%", background: "#1F1F1F",
    border: `1px solid ${err ? "#EF4444" : "#2E2E2E"}`,
    borderRadius: 10, padding: "12px 14px", color: "#F5F5F5",
    fontSize: 15, outline: "none", boxSizing: "border-box",
  }),
  errMsg: { fontSize: 12, color: "#EF4444", marginTop: 5 },
  btnPrimary: {
    width: "100%", padding: 13, borderRadius: 10, border: "none",
    cursor: "pointer", fontWeight: 500, fontSize: 15,
    background: "#E8500A", color: "#fff", marginTop: 4,
    transition: "opacity 0.2s",
  },
  btnGoogle: {
    width: "100%", padding: 13, borderRadius: 10,
    border: "1px solid #2E2E2E", cursor: "pointer", fontWeight: 500,
    fontSize: 15, background: "#1F1F1F", color: "#F5F5F5",
    display: "flex", alignItems: "center", justifyContent: "center", gap: 10,
    marginTop: 4,
  },
  divider:  { display: "flex", alignItems: "center", gap: 12, color: "#555", fontSize: 13, margin: "16px 0" },
  linkRow:  { textAlign: "center", marginTop: "1rem", fontSize: 13, color: "#888" },
  link:     { color: "#E8500A", cursor: "pointer", fontWeight: 500 },
};